config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root "articles#index"
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
#   get 'articles/new' =>'articles#new'
#   get 'articles/index' =>'articles#index'
# get 'articles/index/:title' => 'articles#show'
#   post 'articles/new' => 'articles#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
validates :title,presence: true,length: {minimum: 5,maximum: 10}
validates :description,presence: true, length: {minimum: 5,maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def show
    @article = Article.all
  end

  def new
    @article = Article.new
  end

  def set
    @article = Article.find(params[:title])
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_show_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/articles_controller.rb
#$i=0
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end
  def edit

  end
  def destroy
    @article=Article.find(params[:id])
    #@article.destroy_all
    @article.destroy
    redirect_to articles_path
  end
  def create

    @article = Article.new(article_params)
    if @article.save
    flash[:notice]="Article Successfully created"
    #if $i>4
    redirect_to articles_path
    #else
     # $i+=1
     # redirect_to new_article_path
     # end
    else
      render 'new'
      end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/new.html.erb
<h1>New Article</h1>
<%= form_for :article do |f|%>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %></p>
  <p>
    <%= f.label :description! %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end %>

app/views/article/set.erb
<p>
  Title:
  <%=@article.title%>
</p>
<p>
  Description:
  <%= @article.description %>
</p>

app/views/article/show.html.erb
<h1>Article</h1>
<%= link_to "Create new article path", article_new_path  %>


<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @article.each do |a| %>
    <tr>
      <td><%= a.id %></td>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= form_for(@article) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>Article</h1>
<%= link_to "Create new articles path", new_article_path  %>


<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @article.each do |a| %>
    <tr>
      <td><%= a.id %></td>
      <td><%= a.title %></td>
      <td><%= a.description %></td>
      <td> <%=button_to 'Delete',article_path(a), method: :delete, data:{confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<% if @article.errors.any?  %>
  <ul>
  <% @article.errors.full_messages.each do |m| %>
        <li><%= m %></li>
    <%end %>
  </ul>
  <% end %>
<%= form_for (@article) do |f|%>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %></p>
  <p>
    <%= f.label :description! %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end %>

<%= link_to "Listing Articles", articles_path %>

app/views/articles/show.html.erb
<p>
  Title:
  <%=@article.title%>
</p>
<p>
  Description:
  <%= @article.description %>
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Articles</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', home_path, class:'btn btn-read'%>
      </li>
      <li class="nav-item">
        <%= link_to "About", '#', class: 'btn btn-read' %>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="https://github.com/StephenFiser/FrogBlog/blob/master/app/views/layouts/_navbar.html.erb">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
  <div class="container-fluid ">
    <div class="jumbotron jumbotron-fluid">
      <%=render "layouts/navbar" %>
        <a href="https://www.railstutorial.org/book" >STUDY ABOUT RAILS</a>
 <img src="https://drive.google.com/open?id=1bNUcq6ZeZzlvFQA1G9--o_9EFpuJScaM"  width="75" height="75">
  <% flash.each do |name,msg|  %>
 <ul>
<li><%= msg %></li>
  </ul>
    <% end %>
    <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1 style="color: yellow">ThankYou for visiting</h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/X4t0JxiBeO0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

app/views/pages/home.erb
<h3 style="color: #B00100"> Welcome to home</h3>